# Cvičení 11

## Využití QR rozkladu

V tomto cvičení se budeme zabývat aplikacemi QR rozkladu, konkrétně jeho využitím k výpočtu spektrálního rozkladu matice.

### Spektrální rozklad

Připomeňme, že pokud je $\mathsf{A}$ reálná symetrická matice, pak existují ortogonální matice $\mathsf{Q}$ a diagonální matice $\mathsf{D}$ takové, že $\mathsf{A} = \mathsf{Q}\mathsf{D}\mathsf{Q}^T$. Diagonální prvky $\mathsf{D}$ jsou vlastní čísla matice $\mathsf{A}$, sloupce $\mathsf{Q}$ jsou ortonormální vlastní vektory $\mathsf{A}$. Této maticové dekompozici říkáme spektrální rozklad.

Spektrální rozklad můžeme určit pomocí QR algoritmu (viz přednáška).

### Příklad 1

**ÚKOL**: Vytvořte funkci `qdqt` implementující QR algoritmus pro hledání vlastních čísel a vlastních vektorů. Na vstupu bude mít reálnou symetrickou matici a požadovanou přesnost `eps`. Výstupem bude matice $\mathsf{Q}$, jejíž sloupce budou tvořit vlastní vektory vstupní matice, vektor $\mathbf{d}$ obsahující příslušná vlastní čísla a počet iterací potřebných k dosažené přesnosti. Využijte buď vámi vytvořenou funkci `qr_decomposition(A)` z 5. cvičení (odstraňte příslušné výpisy), případně zabudovanou funkci z NumPy. 

$$
\begin{array}{l}
\text{Input: SPD matrix } A, \text{ tolerance } eps\\
D = A  \\
Q = I \\
\text{\bf{while} } \|D - diag(diag(D))\| > eps  \\
\quad\begin{array}{l}
    [Qk, Rk] = qr(D) \\
    D = Rk*Qk \\ 
    Q = Q*Qk \\
    k = k + 1 \\
\end{array}\\
\text{end while}\\
\text{The solution is stored in } Q \text{ and } diag(D).\\
\end{array}
$$

In [ ]:
import numpy as np

# UKOL: Zkopírujte řešení OR dekompozice z 5. cvičení: 
def qr_decomposition(A):


    return Q, R

# Zde pouze pro otestování
# Q, R = qr_decomposition(A)

In [ ]:
# UKOL: Implementujte QR algoritmus
import numpy as np

def qdqt(A, eps=1e-5):
    """
    QDQT Pocita spektralni rozklad pomoci QR algoritmu
    Vraci ortogonalni matici Q (sloupce jsou ortonormalni vlastni vektory
    A), vektor d obsahujici vlastni cisla matice A a pocet iteraci nutnych
    k dosazeni reseni.
    """
    D = np.copy(A)
    m = A.shape[0]
    Q = np.eye(m)
    
    it = 1
    
    # iterace ukoncime, pokud norma mimodiagonalnich prvku bude dostatecne mala
    while np.linalg.norm(D - np.diag(np.diag(D))) > eps:
        # Implementujte podle výše uvedeného pseudokódu

        it = it + 1

    d = np.diag(D)

    return Q, d, it

In [9]:
# Otestujeme vasi metodu

# Symetricka realna matice

A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])

# Zavolejme qdqt
Q, d, it = qdqt(A)

print("Vstupní matice A:")
print(A)
print("\nOrtogonální matice Q:")
print(Q)
print("\nVlastní čísla (diagonála D):")
print(d)
print("\nPočet iterací:")
print(it)

# Overme, ze A = QDQ^T
D = np.diag(d)
A_reconstructed = Q @ D @ Q.T
print("\nMatice rekonstruovana z QDQ^T:")
print(A_reconstructed)
print("\nRozdil mezi vstupni matici A a rekonstruovanou matici:")
print(np.abs(A - A_reconstructed))

print("\nOverme, ze Q[:,0] je vlastni vektor a d[0] odpovidajici vlastni cislo:")
print('Av = {}'.format(A@Q[:,0]))
print('lambda v = {}'.format(d[0]*Q[:,0]))

Vstupní matice A:
[[1 2 3]
 [2 4 5]
 [3 5 6]]

Ortogonální matice Q:
[[-0.32798528 -0.73697059 -0.59101608]
 [-0.59100905 -0.32799231  0.7369731 ]
 [-0.73697623  0.59101218 -0.32797964]]

Vlastní čísla (diagonála D):
[11.34481428 -0.51572947  0.17091519]

Počet iterací:
12

Matice rekonstruovana z QDQ^T:
[[1.00000571 1.99999771 2.9999993 ]
 [1.99999771 3.99999683 5.00000356]
 [2.9999993  5.00000356 5.99999746]]

Rozdil mezi vstupni matici A a rekonstruovanou matici:
[[5.70817233e-06 2.28870501e-06 7.04976811e-07]
 [2.28870501e-06 3.16783770e-06 3.55897813e-06]
 [7.04976811e-07 3.55897813e-06 2.54033463e-06]]

Overme, ze Q[:,0] je vlastni vektor a d[0] odpovidajici vlastni cislo:
Av = [-3.72093206 -6.70488789 -8.36085845]
lambda v = [-3.72093206 -6.70488789 -8.36085845]
